
```{r}
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(khroma)
library(rstatix)
library(knitr)
library(kableExtra)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
```

```{r}
experiment_slug <- "2024-09-11-vary-struct"
working_directory <- paste(
  "experiments",
  experiment_slug,
  "analysis",
  sep = "/"
)
# Adjust working directory if being knitted for bookdown build.
if (bookdown) {
  working_directory <- paste0(
    bookdown_wd_prefix,
    working_directory
  )
}
```

```{r}
# Configure our default graphing theme
theme_set(theme_cowplot())
# Create a directory to store plots
plot_dir <- paste(
  working_directory,
  "plots",
  sep = "/"
)

dir.create(
  plot_dir,
  showWarnings = FALSE
)
```

```{r}

# Load summary data from final update
data_path <- paste(
  working_directory,
  "data",
  "summary.csv",
  sep = "/"
)
data <- read_csv(data_path)

data <- data %>%
  mutate(
    graph_type = as.factor(graph_type)
  )

```


```{r}

# Grab just completed rows
completed_runs_data <- data %>%
  filter(
    update == 100000
  )

incomplete_runs <- data %>%
  filter(
    update != 100000
  )
```


## Number of tasks completed

```{r}
pop_tasks_total_plt <- ggplot(
  data = completed_runs_data,
  mapping = aes(
    x = graph_type,
    y = pop_task_total,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/pop_tasks_total.pdf"),
  plot = pop_tasks_total_plt,
  width = 15,
  height = 10
)
```

```{r}
dom_tasks_total_plt <- ggplot(
  data = completed_runs_data,
  mapping = aes(
    x = graph_type,
    y = dom_task_total,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/dom_tasks_total.pdf"),
  plot = dom_tasks_total_plt,
  width = 15,
  height = 10
)
```

```{r}
kruskal.test(
  formula = dom_task_total ~ graph_type,
  data = filter(completed_runs_data, graph_type != "star")
)
```

## Number of Equals

```{r}
num_equals_data <- completed_runs_data %>%
  group_by(
    graph_type
  ) %>%
  summarize(
    num_dom_equals = sum(dom_detail_equals),
    no_dom_equals = n() - sum(dom_detail_equals),
    num_pop_equals = sum(pop_task_equals),
    no_pop_equals = n() - sum(pop_task_equals)
  )

fisher_results <- num_equals_data %>%
  filter(graph_type != "star") %>%
  select(
    graph_type, num_pop_equals, no_pop_equals
  ) %>%
  column_to_rownames(
    var = "graph_type"
  ) %>%
  pairwise_fisher_test(
    p.adjust.method = "holm",
  )

fisher_table <- kbl(fisher_results) %>% kable_styling()
save_kable(fisher_table, paste0(plot_dir, "/pop_equals_stats.pdf"))
```

## MRCA Changes

```{r}
mrca_changes_plt <- ggplot(
  data = completed_runs_data,
  mapping = aes(
    x = graph_type,
    y = phylodiv_mrca_changes,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/mrca_changes.pdf"),
  plot = mrca_changes_plt,
  width = 15,
  height = 10
)
```

## Average generation

```{r}
avg_generation_plt <- ggplot(
  data = completed_runs_data,
  mapping = aes(
    x = graph_type,
    y = time_average_generation,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/avg_generation.pdf"),
  plot = avg_generation_plt,
  width = 15,
  height = 10
)
```

## Average generations per sweep

```{r}
avg_gens_per_sweep_plt <- ggplot(
  data = completed_runs_data,
  mapping = aes(
    x = graph_type,
    y = time_average_generation / phylodiv_mrca_changes,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/avg_gens_per_mrca_change.pdf"),
  plot = avg_gens_per_sweep_plt,
  width = 15,
  height = 10
)
```

## Phylogenetic diversity
<!-- phylodiv_current_phylogenetic_diversity
phylodiv_diversity -->

```{r}
cur_phylo_div_plt <- ggplot(
  data = completed_runs_data,
  mapping = aes(
    x = graph_type,
    y = phylodiv_current_phylogenetic_diversity,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/phylodiv_current_phylogenetic_diversity.pdf"),
  plot = cur_phylo_div_plt,
  width = 15,
  height = 10
)
```

```{r}
phylodiv_diversity_plt <- ggplot(
  data = filter(completed_runs_data, graph_type != "star"),
  mapping = aes(
    x = graph_type,
    y = phylodiv_diversity,
    fill = graph_type
  )
) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8
  ) +
  geom_point(
    mapping=aes(color = graph_type),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 30,
      hjust = 1
    )
  )

ggsave(
  filename = paste0(plot_dir, "/genotypic_diversity.pdf"),
  plot = phylodiv_diversity_plt,
  width = 15,
  height = 10
)
```